-- TEST-ONLY migration (lives in src/test/resources, so it never ships in the application jar).
-- Tables for the JPA learning tests in com.masternova.api.learning.jpa — see
-- patterns/java/10-request-lifecycle-and-jpa.md. Even here Flyway owns the schema and Hibernate
-- only validates it, exactly like the real modules.
CREATE TABLE learning_course (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(255) NOT NULL,
    version BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE learning_section (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT       NOT NULL REFERENCES learning_course (id) ON DELETE CASCADE,
    title     VARCHAR(255) NOT NULL,
    position  INT          NOT NULL
);

-- ⭐ Postgres does NOT index foreign keys automatically; every "sections of course X" query needs this.
CREATE INDEX learning_section_course_id_idx ON learning_section (course_id);
